---
abstract: 'Control the Amazon EC2 and Eucalyptus Clouds'
author:
  - 'Lincoln Stein <lincoln.stein@oicr.on.ca>'
build_requires: {}
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VM-EC2
provides:
  VM::EC2:
    file: lib/VM/EC2.pm
    version: 1.18
  VM::EC2::AvailabilityZone:
    file: lib/VM/EC2/AvailabilityZone.pm
    version: 0
  VM::EC2::BlockDevice:
    file: lib/VM/EC2/BlockDevice.pm
    version: 0
  VM::EC2::BlockDevice::Attachment:
    file: lib/VM/EC2/BlockDevice/Attachment.pm
    version: 0
  VM::EC2::BlockDevice::EBS:
    file: lib/VM/EC2/BlockDevice/EBS.pm
    version: 0
  VM::EC2::BlockDevice::Mapping:
    file: lib/VM/EC2/BlockDevice/Mapping.pm
    version: 0
  VM::EC2::BlockDevice::Mapping::EBS:
    file: lib/VM/EC2/BlockDevice/Mapping/EBS.pm
    version: 0
  VM::EC2::Dispatch:
    file: lib/VM/EC2/Dispatch.pm
    version: 0
  VM::EC2::ELB:
    file: lib/VM/EC2/ELB.pm
    version: 0
  VM::EC2::ELB::BackendServerDescription:
    file: lib/VM/EC2/ELB/BackendServerDescription.pm
    version: 0
  VM::EC2::ELB::HealthCheck:
    file: lib/VM/EC2/ELB/HealthCheck.pm
    version: 0
  VM::EC2::ELB::InstanceState:
    file: lib/VM/EC2/ELB/InstanceState.pm
    version: 0
  VM::EC2::ELB::Listener:
    file: lib/VM/EC2/ELB/Listener.pm
    version: 0
  VM::EC2::ELB::ListenerDescription:
    file: lib/VM/EC2/ELB/ListenerDescription.pm
    version: 0
  VM::EC2::ELB::Policies:
    file: lib/VM/EC2/ELB/Policies.pm
    version: 0
  VM::EC2::ELB::Policies::AppCookieStickinessPolicy:
    file: lib/VM/EC2/ELB/Policies/AppCookieStickinessPolicy.pm
    version: 0
  VM::EC2::ELB::Policies::LBCookieStickinessPolicy:
    file: lib/VM/EC2/ELB/Policies/LBCookieStickinessPolicy.pm
    version: 0
  VM::EC2::ELB::PolicyAttribute:
    file: lib/VM/EC2/ELB/PolicyAttribute.pm
    version: 0
  VM::EC2::ELB::PolicyAttributeType:
    file: lib/VM/EC2/ELB/PolicyAttributeType.pm
    version: 0
  VM::EC2::ELB::PolicyDescription:
    file: lib/VM/EC2/ELB/PolicyDescription.pm
    version: 0
  VM::EC2::ELB::PolicyTypeDescription:
    file: lib/VM/EC2/ELB/PolicyTypeDescription.pm
    version: 0
  VM::EC2::ElasticAddress:
    file: lib/VM/EC2/ElasticAddress.pm
    version: 0
  VM::EC2::Error:
    file: lib/VM/EC2/Error.pm
    version: 0
  VM::EC2::Generic:
    file: lib/VM/EC2/Generic.pm
    version: 0
  VM::EC2::Group:
    file: lib/VM/EC2/Group.pm
    version: 0
  VM::EC2::Image:
    file: lib/VM/EC2/Image.pm
    version: 0
  VM::EC2::Image::LaunchPermission:
    file: lib/VM/EC2/Image/LaunchPermission.pm
    version: 0
  VM::EC2::Instance:
    file: lib/VM/EC2/Instance.pm
    version: 0
  VM::EC2::Instance::ConsoleOutput:
    file: lib/VM/EC2/Instance/ConsoleOutput.pm
    version: 0
  VM::EC2::Instance::IamProfile:
    file: lib/VM/EC2/Instance/IamProfile.pm
    version: 0
  VM::EC2::Instance::Metadata:
    file: lib/VM/EC2/Instance/Metadata.pm
    version: 0
  VM::EC2::Instance::MonitoringState:
    file: lib/VM/EC2/Instance/MonitoringState.pm
    version: 0
  VM::EC2::Instance::PasswordData:
    file: lib/VM/EC2/Instance/PasswordData.pm
    version: 0
  VM::EC2::Instance::Placement:
    file: lib/VM/EC2/Instance/Placement.pm
    version: 0
  VM::EC2::Instance::Set:
    file: lib/VM/EC2/Instance/Set.pm
    version: 0
  VM::EC2::Instance::State:
    file: lib/VM/EC2/Instance/State.pm
    version: 0
  VM::EC2::Instance::State::Change:
    file: lib/VM/EC2/Instance/State/Change.pm
    version: 0
  VM::EC2::Instance::Status:
    file: lib/VM/EC2/Instance/Status.pm
    version: 0
  VM::EC2::Instance::Status::Details:
    file: lib/VM/EC2/Instance/Status/Details.pm
    version: 0
  VM::EC2::Instance::Status::Event:
    file: lib/VM/EC2/Instance/Status/Event.pm
    version: 0
  VM::EC2::Instance::StatusItem:
    file: lib/VM/EC2/Instance/StatusItem.pm
    version: 0
  VM::EC2::KeyPair:
    file: lib/VM/EC2/KeyPair.pm
    version: 0
  VM::EC2::NetworkInterface:
    file: lib/VM/EC2/NetworkInterface.pm
    version: 0
  VM::EC2::NetworkInterface::Association:
    file: lib/VM/EC2/NetworkInterface/Association.pm
    version: 0
  VM::EC2::NetworkInterface::Attachment:
    file: lib/VM/EC2/NetworkInterface/Attachment.pm
    version: 0
  VM::EC2::NetworkInterface::PrivateIpAddress:
    file: lib/VM/EC2/NetworkInterface/PrivateIpAddress.pm
    version: 0
  VM::EC2::ProductCode:
    file: lib/VM/EC2/ProductCode.pm
    version: 0
  VM::EC2::Region:
    file: lib/VM/EC2/Region.pm
    version: 0
  VM::EC2::ReservationSet:
    file: lib/VM/EC2/ReservationSet.pm
    version: 0
  VM::EC2::ReservedInstance:
    file: lib/VM/EC2/ReservedInstance.pm
    version: 0
  VM::EC2::ReservedInstance::Offering:
    file: lib/VM/EC2/ReservedInstance/Offering.pm
    version: 0
  VM::EC2::Security::Credentials:
    file: lib/VM/EC2/Security/Credentials.pm
    version: 0
  VM::EC2::Security::FederatedUser:
    file: lib/VM/EC2/Security/FederatedUser.pm
    version: 0
  VM::EC2::Security::Policy:
    file: lib/VM/EC2/Security/Policy.pm
    version: 0
  VM::EC2::Security::Token:
    file: lib/VM/EC2/Security/Token.pm
    version: 0
  VM::EC2::SecurityGroup:
    file: lib/VM/EC2/SecurityGroup.pm
    version: 0
  VM::EC2::SecurityGroup::GroupPermission:
    file: lib/VM/EC2/SecurityGroup/GroupPermission.pm
    version: 0
  VM::EC2::SecurityGroup::IpPermission:
    file: lib/VM/EC2/SecurityGroup/IpPermission.pm
    version: 0
  VM::EC2::Snapshot:
    file: lib/VM/EC2/Snapshot.pm
    version: 0
  VM::EC2::Snapshot::CreateVolumePermission:
    file: lib/VM/EC2/Snapshot/CreateVolumePermission.pm
    version: 0
  VM::EC2::Spot::DatafeedSubscription:
    file: lib/VM/EC2/Spot/DatafeedSubscription.pm
    version: 0
  VM::EC2::Spot::InstanceRequest:
    file: lib/VM/EC2/Spot/InstanceRequest.pm
    version: 0
  VM::EC2::Spot::LaunchSpecification:
    file: lib/VM/EC2/Spot/LaunchSpecification.pm
    version: 0
  VM::EC2::Spot::PriceHistory:
    file: lib/VM/EC2/Spot/PriceHistory.pm
    version: 0
  VM::EC2::Staging::Manager:
    file: lib/VM/EC2/Staging/Manager.pm
    version: 0
  VM::EC2::Staging::Server:
    file: lib/VM/EC2/Staging/Server.pm
    version: 0
  VM::EC2::Staging::Volume:
    file: lib/VM/EC2/Staging/Volume.pm
    version: 0
  VM::EC2::State::Reason:
    file: lib/VM/EC2/Instance/State/Reason.pm
    version: 0
  VM::EC2::Tag:
    file: lib/VM/EC2/Tag.pm
    version: 0
  VM::EC2::VPC:
    file: lib/VM/EC2/VPC.pm
    version: 0
  VM::EC2::VPC::CustomerGateway:
    file: lib/VM/EC2/VPC/CustomerGateway.pm
    version: 0
  VM::EC2::VPC::DhcpOptions:
    file: lib/VM/EC2/VPC/DhcpOptions.pm
    version: 0
  VM::EC2::VPC::InternetGateway:
    file: lib/VM/EC2/VPC/InternetGateway.pm
    version: 0
  VM::EC2::VPC::InternetGateway::Attachment:
    file: lib/VM/EC2/VPC/InternetGateway/Attachment.pm
    version: 0
  VM::EC2::VPC::NetworkAcl:
    file: lib/VM/EC2/VPC/NetworkAcl.pm
    version: 0
  VM::EC2::VPC::NetworkAcl::Association:
    file: lib/VM/EC2/VPC/NetworkAcl/Association.pm
    version: 0
  VM::EC2::VPC::NetworkAcl::Entry:
    file: lib/VM/EC2/VPC/NetworkAcl/Entry.pm
    version: 0
  VM::EC2::VPC::Route:
    file: lib/VM/EC2/VPC/Route.pm
    version: 0
  VM::EC2::VPC::RouteTable:
    file: lib/VM/EC2/VPC/RouteTable.pm
    version: 0
  VM::EC2::VPC::RouteTable::Association:
    file: lib/VM/EC2/VPC/RouteTable/Association.pm
    version: 0
  VM::EC2::VPC::Subnet:
    file: lib/VM/EC2/VPC/Subnet.pm
    version: 0
  VM::EC2::VPC::VpnConnection:
    file: lib/VM/EC2/VPC/VpnConnection.pm
    version: 0
  VM::EC2::VPC::VpnGateway:
    file: lib/VM/EC2/VPC/VpnGateway.pm
    version: 0
  VM::EC2::VPC::VpnGateway::Attachment:
    file: lib/VM/EC2/VPC/VpnGateway/Attachment.pm
    version: 0
  VM::EC2::VPC::VpnTunnelTelemetry:
    file: lib/VM/EC2/VPC/VpnTunnelTelemetry.pm
    version: 0
  VM::EC2::Volume:
    file: lib/VM/EC2/Volume.pm
    version: 0
  VM::EC2::Volume::Status:
    file: lib/VM/EC2/Volume/Status.pm
    version: 0
  VM::EC2::Volume::Status::Action:
    file: lib/VM/EC2/Volume/Status/Action.pm
    version: 0
  VM::EC2::Volume::Status::Details:
    file: lib/VM/EC2/Volume/Status/Details.pm
    version: 0
  VM::EC2::Volume::Status::Event:
    file: lib/VM/EC2/Volume/Status/Event.pm
    version: 0
  VM::EC2::Volume::StatusItem:
    file: lib/VM/EC2/Volume/StatusItem.pm
    version: 0
requires:
  Digest::SHA: 5.47
  File::Path: 2.08
  LWP: 5.835
  MIME::Base64: 3.08
  URI::URL: 5.03
  XML::Simple: 2.18
resources:
  license: http://dev.perl.org/licenses/
version: 1.18
